version: '3.8'

services:
  notemaster:
    build: .
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AI_PROVIDER=groq
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - notemaster_data:/app/server/data
    restart: unless-stopped
    container_name: notemaster-app

volumes:
  notemaster_data:
    driver: local
